apiVersion: apps/v1
kind: Deployment

metadata:
  name: log-output-dep
  namespace: log-output-ns
  labels:
    app: log-output

spec:
  selector:
    matchLabels:
      app: log-output

  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-volume
          persistentVolumeClaim:
            claimName: log-output-pvc
            

      containers:
      - name: log-output-reader
        image: hiiamtrong/log-output:latest
        command:
          - "/bin/sh"
        args:
          - "-c"
          - ./reader
        volumeMounts:
          - name: log-output-volume
            mountPath: /tmp
          
      - name: log-output-writer
        image: hiiamtrong/log-output:latest
        command:
          - "/bin/sh"
        args:
          - "-c"
          - ./writer
        volumeMounts:
          - name: log-output-volume
            mountPath: /tmp
    