apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  labels:
    app: log-output
  namespace: log-output-ns
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
  - port: 3000
    targetPort: 8080
    protocol: TCP
