apiVersion: apps/v1
kind: Deployment

metadata:
  name: ping-pong-dep


  labels:
    app: ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: hiiamtrong/ping-pong:latest
          volumeMounts:
              - name: ping-pong-env
                mountPath: /usr/src/app/.env
                subPath: .env

                
      volumes:
        - name: ping-pong-env
          configMap:
            name: pingpong-cm
            items:
              - key: env
                path: .env