apiVersion: apps/v1
kind: Deployment

metadata:
  name: ping-pong-dep
  namespace: log-output-ns

  labels:
    app: ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: hiiamtrong/ping-pong:latest
          volumeMounts:
              - name: ping-pong-volume
                mountPath: /tmp
                
      volumes:
        - name: ping-pong-volume
          persistentVolumeClaim:
            claimName: log-output-pvc