apiVersion: v1
kind: Service

metadata:
  name: ping-pong-svc
  namespace: log-output-ns
  labels:
    app: ping-pong
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
      - protocol: TCP
        port: 2223
        targetPort: 9090
    