apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-simple-dep
  labels:
    app: todo-simple
  namespace: todo-ns 
spec:
  selector:
    matchLabels:
      app: todo-simple
  template:
    metadata:
      labels:
        app: todo-simple
    spec:
      
      volumes:
        - name: todo-simple-volume
          persistentVolumeClaim:
            claimName: todo-simple-pvc
        - name: config
          configMap:
            name: todo-simple-cm
            items:
              - key: .env
                path: .env

      containers:
        - name: todo-simple-client
          image: hiiamtrong/todo-simple:latest
          command:
            - "/bin/sh"
          args:
            - -c
            - ./client
          volumeMounts:
            - mountPath: /usr/src/app/public
              name: todo-simple-volume

            - mountPath: /usr/src/app/.env
              subPath: .env
              readOnly: true
              name: config


        - name: todo-simple-server
          image: hiiamtrong/todo-simple:latest
          volumeMounts:
            - mountPath: /usr/src/app/.env
              subPath: .env
              readOnly: true
              name: config
          command:
            - "/bin/sh"
          args:
            - -c
            - ./server
          
      
