apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-simple-pvc
spec:
  storageClassName: todo-simple-sc
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
