apiVersion: v1
kind: Service

metadata:
  name: todo-simple-svc
spec:
  type: NodePort
  selector:
    app: todo-simple

  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 2222
      targetPort: 3333
