apiVersion: v1
kind: Service

metadata:
  name: todo-simple-svc
  labels:
    app: todo-simple
  namespace: todo-ns 
spec:
  type: ClusterIP
  selector:
    app: todo-simple
  ports:
      - protocol: TCP
        port: 2222
        targetPort: 8080
        name: client
  
      - protocol: TCP
        port: 3333
        targetPort: 9090
        name: server